### ISSUE TITLE
how does this show an address change example?

### ISSUE THREAD

**Issue by G2G2G2G** [fabyte/Tiny_BME280_Arduino_Library#2]
https://github.com/fabyte/Tiny_BME280_Arduino_Library/blob/master/examples/Example5_Settings/Example5_Settings.ino

Line 14 says `Serial.println("Example showing alternate I2C addresses");`

Do you mean to call `setI2CAddress` I think? from reading the code

or is the `mySensor.beginI2C();` calls the 0x76 address? I am noob

**Comment by fabyte** [comment]
@G2G2G2G You're right, this is example is meant to demonstrate how to set the various filter and oversample settings of the BME280. You can see the method calls in the example that do that:

```
mySensor.setFilter(1); //0 to 4 is valid. Filter coefficient. See 3.4.4
mySensor.setStandbyTime(0); //0 to 7 valid. Time between readings. See table 27.

mySensor.setTempOverSample(1); //0 to 16 are valid. 0 disables temp sensing. See table 24.
mySensor.setPressureOverSample(1); //0 to 16 are valid. 0 disables pressure sensing. See table 23.
mySensor.setHumidityOverSample(1); //0 to 16 are valid. 0 disables humidity sensing. See table 19.
```

In fact, the serial print `"Example showing alternate I2C addresses"` is wrong in this example (copy/paste error) and should be fixed.

**Comment by fabyte** [comment]
@G2G2G2G see this for an example3 of using different I2C addresses.

There are multiple ways to do this:
1.
```
mySensor.setI2CAddress(0x76);
mySensor.begin();
```
2. 
```
mySensor.beginI2C(0x76);
```

The second way is a combination of the first two method calls.

**Comment by G2G2G2G** [comment]
Ok that's good, looks like I figured out the:
```
mySensor.beginI2C(0x76);
```
correctly. Through testing all of the functions in the main program, thanks!
